apiVersion: v1
kind: ConfigMap
metadata:
  name: cvm-catalyst-config
  namespace: {{ include "cvm-catalyst.namespace" . }}
  labels:
    app.kubernetes.io/name: cvm-catalyst
data:
  API_PORT: {{ .Values.config.API_PORT | quote }}
  API_HOST: {{ .Values.config.API_HOST | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.config.NEXT_PUBLIC_API_URL | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
