apiVersion: v1
kind: Service
metadata:
  name: cvm-catalyst-frontend
  namespace: {{ include "cvm-catalyst.namespace" . }}
  labels:
    app.kubernetes.io/name: cvm-catalyst-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cvm-catalyst-frontend
  ports:
    - name: http
      port: 3000
      targetPort: {{ .Values.frontend.containerPort }}
